- processor:
  - description: "LEMMA MongoDB Generator"
  - docker:
    - image: "lemma/mongodb_generator:latest"
    - repository: "repository.seelab.fh-dortmund.de:51900"
    - buildscript: "./build.sh"
    - lemma_version_file: "../pom.xml"

- required_args:
  - builtin:
    - intermediate_model: "path to intermediate operation model (must be relative to model base path)"
    - target_folder: "path to generation target folder"